### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by z-banu** [lthoang/simple-c-ast#1]
Hi ! I started learning java from past a month . I have a basic knowledge about java . Can u tell me how to run your code  ." import java_cup.runtime.Symbol;" this package doesn't exists .  I have cloned ur project exactly the way u have uploaded . It has all jflex nd Cup files . Please help me out . Thank u .

**Comment by lthoang** [comment]
Hi z-banu,

I just push a new commit with fixed project setup. Please pull the source an run again.

Regards,
Hoang

**Comment by z-banu** [comment]
Thank you Sir ! Can you explain hierarchy of your code .

Regards,
z-banu

**Comment by lthoang** [comment]
Hi z-banu,

The source code is a demo of using CUP and JFlex for Simple version of C language. The structure of code can be explained briefly as below:

* **Generated code:** Including file sym.java, parser.java, and Scanner.java. If you are using windows, then you can directly execute file `generate.bat` at `resources` directory to generate these files. You can find further information of how to use Jflex and CUP its [officical site](http://jflex.de/manual.html).
* SimpleCParser.java: This main class is for printing AST structure to a text file. You can find example of output file at `etc` directory, such as file `test0-ast.txt`. The input arguments for this class are `inputFileDirectory` and `outputFileDirectory`.
* SimpleCLexer.java: This main class is a Scanner which is used for print all scanned tokens to text file. Similarly, example of output file you can find at `etc` directory (file `test0-lex.txt`). Input arguments are similar to the previous one.
* Ast.java: Abstract Syntax Tree printer for Simple C syntax.
* ...

Regards,
Hoang

**Comment by z-banu** [comment]
Thank You !

**Comment by z-banu** [comment]
Sir ! I am getting an error , javac is an invalid post and usage <javac> <source file >.
Sir can u tell me how to execute "SimpleCParser.java" . Sorry for the inconvenience . Thank you .

**Comment by z-banu** [comment]
C:\Users\Zuvariya Banu\Desktop\simple-c-ast-master\simple-c-ast-master\src\main\
java\com\trhoanglee\ast>javac SimpleCParser.java
SimpleCParser.java:33: error: cannot find symbol
        parser P = new parser(new Scanner(inFile));
        ^
  symbol:   class parser
  location: class SimpleCParser
SimpleCParser.java:33: error: cannot find symbol
        parser P = new parser(new Scanner(inFile));
                       ^
  symbol:   class parser
  location: class SimpleCParser
SimpleCParser.java:33: error: cannot find symbol
        parser P = new parser(new Scanner(inFile));
                                  ^
  symbol:   class Scanner
  location: class SimpleCParser
SimpleCParser.java:34: error: cannot find symbol
        Program root = null;
        ^
  symbol:   class Program
  location: class SimpleCParser
SimpleCParser.java:37: error: cannot find symbol
            root = (Program) P.parse().value;
                    ^
  symbol:   class Program
  location: class SimpleCParser
5 errors

**Comment by lthoang** [comment]
Hi z-banu,

Please noted that you need to go to resources directory `src/resources` then execute the `generate.bat` file. This step is to generate 3 files `parser.java`, `Scanner.java`, and `sym.java`. When you done this step you may execute your source code.
If you still got the errors, please describe your steps.

**Comment by z-banu** [comment]
Sir first I executed generate.bat , it created 3 files parser.java , Scanner.java,Sym.java , Then bold the commands , please check and help me sir. Thank you :) .

**C:\Users\Zuvariya Banu\Desktop\simple-c-ast-master\simple-c-ast-master\src\main\
resources>generate.bat**

C:\Users\Zuvariya Banu\Desktop\simple-c-ast-master\simple-c-ast-master\src\main\
resources>java -jar libs/jflex-1.6.1.jar -d ../java/com/trhoanglee/ast SimpleC.l
ex
Reading "SimpleC.lex"

Warning in file "SimpleC.lex" (line 173):
Expression matches the empty string, which may lead to non-termination.
    ([^*]|"*"[^/])*      { /* ignore */  }
Constructing NFA : 256 states in NFA
Converting NFA to DFA :
................................................................................
........................................
124 states before minimization, 108 states in minimized DFA
Old file "..\java\com\trhoanglee\ast\Scanner.java" saved as "..\java\com\trhoang
lee\ast\Scanner.java~"
Writing code to "..\java\com\trhoanglee\ast\Scanner.java"

C:\Users\Zuvariya Banu\Desktop\simple-c-ast-master\simple-c-ast-master\src\main\
resources>java -jar libs/java-cup-11a.jar -interface -destdir ../java/com/trhoan
glee/ast SimpleC.cup
------- CUP v0.11a beta 20060608 Parser Generation Summary -------
  0 errors and 0 warnings
  48 terminals, 34 non-terminals, and 90 productions declared,
  producing 172 unique parse states.
  0 terminals declared but not used.
  0 non-terminals declared but not used.
  0 productions never reduced.
  0 conflicts detected (0 expected).
  Code written to "parser.java", and "sym.java".
---------------------------------------------------- (v0.11a beta 20060608)


**C:\Users\Zuvariya Banu\Desktop\simple-c-ast-master\simple-c-ast-master\src\main\
java\com\trhoanglee\ast>javac SimpleCParser.java**
SimpleCParser.java:33: error: cannot find symbol
        parser P = new parser(new Scanner(inFile));
        ^
  symbol:   class parser
  location: class SimpleCParser
SimpleCParser.java:33: error: cannot find symbol
        parser P = new parser(new Scanner(inFile));
                       ^
  symbol:   class parser
  location: class SimpleCParser
SimpleCParser.java:33: error: cannot find symbol
        parser P = new parser(new Scanner(inFile));
                                  ^
  symbol:   class Scanner
  location: class SimpleCParser
SimpleCParser.java:34: error: cannot find symbol
        Program root = null;
        ^
  symbol:   class Program
  location: class SimpleCParser
SimpleCParser.java:37: error: cannot find symbol
            root = (Program) P.parse().value;
                    ^
  symbol:   class Program
  location: class SimpleCParser
5 errors

**Comment by lthoang** [comment]
Oh. I got your point. You're having problem in linking external classpath/libraries. Here is the trick:
After compiled your source code, assuming that the current directory is the project root folder. You can execute the following command:

```
java -classpath src/main/resources/libs/java-cup-11a.jar;src/main/resources/libs/jflex-1.6.1.jar;target/classes com.trhoanglee.ast.SimpleCParser <input_file> <output_file>
```

**Comment by z-banu** [comment]
Sir ! Its saying it cant find the path . 

**C:\Users\Zuvariya Banu\Desktop\simple-c-ast-master\simple-c-ast-master>java -cla
sspath src\main\resources\libs\java-cup-11a.jar;**
Usage: java [-options] class [args...]
           (to execute a class)
   or  java [-options] -jar jarfile [args...]
           (to execute a jar file)
where options include:
    -d32          use a 32-bit data model if available
    -d64          use a 64-bit data model if available
    -server       to select the "server" VM
                  The default VM is server.

    -cp <class search path of directories and zip/jar files>
    -classpath <class search path of directories and zip/jar files>
                  A ; separated list of directories, JAR archives,
                  and ZIP archives to search for class files.
    -D<name>=<value>
                  set a system property
    -verbose:[class|gc|jni]
                  enable verbose output
    -version      print product version and exit
    -version:<value>
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  require the specified version to run
    -showversion  print product version and continue
    -jre-restrict-search | -no-jre-restrict-search
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  include/exclude user private JREs in the version search
    -? -help      print this help message
    -X            print help on non-standard options
    -ea[:<packagename>...|:<classname>]
    -enableassertions[:<packagename>...|:<classname>]
                  enable assertions with specified granularity
    -da[:<packagename>...|:<classname>]
    -disableassertions[:<packagename>...|:<classname>]
                  disable assertions with specified granularity
    -esa | -enablesystemassertions
                  enable system assertions
    -dsa | -disablesystemassertions
                  disable system assertions
    -agentlib:<libname>[=<options>]
                  load native agent library <libname>, e.g. -agentlib:hprof
                  see also, -agentlib:jdwp=help and -agentlib:hprof=help
    -agentpath:<pathname>[=<options>]
                  load native agent library by full pathname
    -javaagent:<jarpath>[=<options>]
                  load Java programming language agent, see java.lang.instrument

    -splash:<imagepath>
                  show splash screen with specified image
See http://www.oracle.com/technetwork/java/javase/documentation/index.html for m
ore details.

**C:\Users\Zuvariya Banu\Desktop\simple-c-ast-master\simple-c-ast-master>java -cla
sspath src\main\resources\libs\jfle-1.6.1.jar;**
Usage: java [-options] class [args...]
           (to execute a class)
   or  java [-options] -jar jarfile [args...]
           (to execute a jar file)
where options include:
    -d32          use a 32-bit data model if available
    -d64          use a 64-bit data model if available
    -server       to select the "server" VM
                  The default VM is server.

    -cp <class search path of directories and zip/jar files>
    -classpath <class search path of directories and zip/jar files>
                  A ; separated list of directories, JAR archives,
                  and ZIP archives to search for class files.
    -D<name>=<value>
                  set a system property
    -verbose:[class|gc|jni]
                  enable verbose output
    -version      print product version and exit
    -version:<value>
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  require the specified version to run
    -showversion  print product version and continue
    -jre-restrict-search | -no-jre-restrict-search
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  include/exclude user private JREs in the version search
    -? -help      print this help message
    -X            print help on non-standard options
    -ea[:<packagename>...|:<classname>]
    -enableassertions[:<packagename>...|:<classname>]
                  enable assertions with specified granularity
    -da[:<packagename>...|:<classname>]
    -disableassertions[:<packagename>...|:<classname>]
                  disable assertions with specified granularity
    -esa | -enablesystemassertions
                  enable system assertions
    -dsa | -disablesystemassertions
                  disable system assertions
    -agentlib:<libname>[=<options>]
                  load native agent library <libname>, e.g. -agentlib:hprof
                  see also, -agentlib:jdwp=help and -agentlib:hprof=help
    -agentpath:<pathname>[=<options>]
                  load native agent library by full pathname
    -javaagent:<jarpath>[=<options>]
                  load Java programming language agent, see java.lang.instrument

    -splash:<imagepath>
                  show splash screen with specified image
See http://www.oracle.com/technetwork/java/javase/documentation/index.html for m
ore details.

**C:\Users\Zuvariya Banu\Desktop\simple-c-ast-master\simple-c-ast-master>target\cl
asses src\main\java\com.trhoanglee.ast.SimpleCParser test0.c test0ast.txt
The system cannot find the path specified.**

**C:\Users\Zuvariya Banu\Desktop\simple-c-ast-master\simple-c-ast-master>target\cl
asses src\main\java\com\trhoanglee\ast\SimpleCParser.java test0.c test0ast.txt
The system cannot find the path specified.**

**C:\Users\Zuvariya Banu\Desktop\simple-c-ast-master\simple-c-ast-master>target\cl
asses C:\Users\Zuvariya Banu\Desktop\simple-c-ast-master\simple-c-ast-master\src
\main\java\com\trhoanglee\ast SimpleCParser.java test0.c test0ast.txt**
The system cannot find the path specified.

C:\Users\Zuvariya Banu\Desktop\simple-c-ast-master\simple-c-ast-master>

**Comment by lthoang** [comment]
Please copy your command here

**Comment by z-banu** [comment]
C:\Users\Zuvariya Banu\Desktop\simple-c-ast-master\simple-c-ast-master>java -cla
sspath src\main\resources\libs\java-cup-11a.jar;

C:\Users\Zuvariya Banu\Desktop\simple-c-ast-master\simple-c-ast-master>java -cla
sspath src\main\resources\libs\jfle-1.6.1.jar;

C:\Users\Zuvariya Banu\Desktop\simple-c-ast-master\simple-c-ast-master>target\cl
asses C:\Users\Zuvariya Banu\Desktop\simple-c-ast-master\simple-c-ast-master\src
\main\java\com\trhoanglee\ast SimpleCParser.java test0.c test0ast.txt

**Comment by lthoang** [comment]
Please try again with full command here:

```
java -classpath src/main/resources/libs/java-cup-11a.jar;src/main/resources/libs/jflex-1.6.1.jar;target/classes com.trhoanglee.ast.SimpleCParser etc/test0.c test0ast.txt
```

**Comment by z-banu** [comment]
**C:\Users\Zuvariya Banu\Desktop\simple-c-ast-master\simple-c-ast-master>java -cla
sspath src/main/resources/libs/java-cup-11a.jar;src/main/resources/libs/jflex-1.
6.1.jar;target/classes com.trhoanglee.ast.SimpleCParser etc/test0.c test0ast.txt**

Error: Could not find or load main class com.trhoanglee.ast.SimpleCParser

**C:\Users\Zuvariya Banu\Desktop\simple-c-ast-master\simple-c-ast-master>java -cla
sspath src/main/resources/libs/java-cup-11a.jar;src/main/resources/libs/jflex-1.
6.1.jar;target/classes src/main/java/com.trhoanglee.ast.SimpleCParser etc/test0.
c test0ast.txt**
Error: Could not find or load main class src.main.java.com.trhoanglee.ast.Simple
CParser

**Comment by lthoang** [comment]
Have you compiled the source code by using maven? As showed below:

```
mvn clean install
```
